"""Add cascade delete to training entries

Revision ID: 4bc7985031b9
Revises: d6a271d7e9f4
Create Date: 2026-09-19 20:20:12.023935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc7985031b9'
down_revision: Union[str, Sequence[str], None] = 'd6a271d7e9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_weapons_session_id_fkey'), 'sessions_weapons', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_weapons_session_id_fkey'), 'sessions_weapons', 'training_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_weapons_session_id_fkey'), 'sessions_weapons', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_weapons_session_id_fkey'), 'sessions_weapons', 'training_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
