"""add sessions_weapons table

Revision ID: b9fd97b01238
Revises: f55f9f7bc5b7
Create Date: 2026-08-27 13:36:14.651558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9fd97b01238'
down_revision: Union[str, Sequence[str], None] = 'f55f9f7bc5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_weapons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('magazines_count', sa.Integer(), nullable=True),
    sa.Column('rounds_per_magazine', sa.Integer(), nullable=True),
    sa.Column('rounds_fired', sa.Integer(), nullable=False),
    sa.Column('ammo_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions_weapons')
    # ### end Alembic commands ###
