"""add is_active to weapons

Revision ID: c389923bb74f
Revises: b9fd97b01238
Create Date: 2026-09-09 15:50:22.770411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c389923bb74f'
down_revision: Union[str, Sequence[str], None] = 'b9fd97b01238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapons', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapons', 'is_active')
    # ### end Alembic commands ###
