"""add is_owned to weapons

Revision ID: d6a271d7e9f4
Revises: c389923bb74f
Create Date: 2026-09-14 13:27:33.108066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a271d7e9f4'
down_revision: Union[str, Sequence[str], None] = 'c389923bb74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapons', sa.Column('is_owned', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapons', 'is_owned')
    # ### end Alembic commands ###
