"""Add is_seed flag to weapons and training sessions

Revision ID: f3dbda3641d1
Revises: 4bc7985031b9
Create Date: 2026-09-23 15:16:02.965553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3dbda3641d1'
down_revision: Union[str, Sequence[str], None] = '4bc7985031b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_sessions', sa.Column('is_seed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('weapons', sa.Column('is_seed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapons', 'is_seed')
    op.drop_column('training_sessions', 'is_seed')
    # ### end Alembic commands ###
