name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: shooting_user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: shooting_log
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://shooting_user:pass@localhost:5432/shooting_log

    steps:
      - name: Checkout kodu
        uses: actions/checkout@v4
      - name: Ustaw Pythona
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Lint
        run: ruff check .
      - name: Alembic upgrade
        run: alembic upgrade head
      - name: Running pytest
        run: pytest

